---
- name: Add hypervisor host to oVirt Engine
  hosts: localhost
  gather_facts: false

  vars:
    ovirt_engine_url: "https://ovirt.internal.cloudapp.net/ovirt-engine/api"
    ovirt_engine_user: "admin@ovirt@internalsso"
    ovirt_engine_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;prod
          61336134343236343735306165353535306139656133613331653431663934396236313337636364
          6132303463343332363730653366623735313034366536330a626165313364376266633539366663
          38643235663263343335363464306139326466373338393666653662336234383238333034633762
          6366393337623338620a336439653637656166346662306531393035633335623039356134313534
          6334
    ovirt_host_name: "host1"
    ovirt_host_address: "host1.internal.cloudapp.net"
    datacenter_name: "Default"
    cluster_name: "Default"

  tasks:
    - name: Obtain SSO token
      ovirt.ovirt.ovirt_auth:
        url: "{{ ovirt_engine_url }}"
        username: "{{ ovirt_engine_user }}"
        password: "{{ ovirt_engine_password }}"
        insecure: true  # Set to false in production with valid certs
      register: ovirt_auth
      no_log: true  # Don't log credentials

    - name: Display authentication status
      ansible.builtin.debug:
        msg: "Successfully authenticated to oVirt Engine"

    - name: Ensure datacenter exists
      ovirt.ovirt.ovirt_datacenter:
        auth: "{{ ovirt_auth.ansible_facts.ovirt_auth }}"
        name: "{{ datacenter_name }}"
        description: "Default datacenter"
        comment: "Created by Ansible"
        compatibility_version: "4.7"
        local: true
        state: present

    - name: Ensure cluster exists
      ovirt.ovirt.ovirt_cluster:
        auth: "{{ ovirt_auth.ansible_facts.ovirt_auth }}"
        name: "{{ cluster_name }}"
        description: "Default cluster"
        data_center: "{{ datacenter_name }}"
        compatibility_version: "4.7"
        state: present

    - name: Add host to oVirt Engine
      ovirt.ovirt.ovirt_host:
        auth: "{{ ovirt_auth.ansible_facts.ovirt_auth }}"
        name: "{{ ovirt_host_name }}"
        address: "{{ ovirt_host_address }}"
        cluster: "{{ cluster_name }}"
        password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;prod
          39653465363136363132393662373763336537343364623834656435333836656338306338343432
          6566356236626237396163666131323937346565383063340a353533366661303431633863653264
          65316638363535316163366666383839646234613533383635373465366434666661383239313564
          6563643033383861660a366638653065353636653939356665646435376538613032383262373363
          3364
        public_key: false
        state: present
        timeout: 1200
        override_iptables: true
      register: host_result

    - name: Display host addition result
      ansible.builtin.debug:
        msg:
          - "Host addition initiated: {{ ovirt_host_name }}"
          - "Status: {{ host_result.host.status | default('Unknown') }}"

    - name: Wait for host to become 'Up'
      ovirt.ovirt.ovirt_host_info:
        auth: "{{ ovirt_auth.ansible_facts.ovirt_auth }}"
        pattern: "name={{ ovirt_host_name }}"
      register: host_info
      until: host_info.ovirt_hosts[0].status == 'up'
      retries: 60
      delay: 10
      when: host_result.changed

    - name: Display final host status
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Host successfully added to oVirt!"
          - "=========================================="
          - "Host: {{ ovirt_host_name }}"
          - "Cluster: {{ cluster_name }}"
          - "Status: {{ host_info.ovirt_hosts[0].status }}"
          - "=========================================="
      when: host_result.changed

    - name: Revoke SSO token
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth.ansible_facts.ovirt_auth }}"
